package BDDquickstock.SupportClasses;

import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Adds a copy of project QS_QuickStock parameters
 */
public class ProjectParameters {
  /**
   *
   */
  public static String TypeProductName = "";
}
